spring:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  datasource:
    initialize: true
    url: jdbc:h2:mem:ticketsdb
    username: user
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8081

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            jdbc:
              DataSourceInitializer: DEBUG
            orm:
              jpa: DEBUG
        jdbc:
          datasource:
            init:
              ScriptUtils: DEBUG
tickets:
  ttl: 10